pipeline {
    agent any
    environment {
        SONAR_URL = 'http://amrashraf.com:9000/sonarqube'
        SONAR_PROJECT_KEY = 'my-java-app'
        SONAR_PROJECT_NAME = 'my-java-app'
        version = "v${BUILD_NUMBER}"
    }
    stages {
        stage('Checkout') {
            steps {
                script {
                    def gitCredentialsId = 'github_key'
                    checkout([
                        $class: 'GitSCM',
                        branches: [[name: 'develop']],
                        userRemoteConfigs: [[
                            url: 'https://github.com/amrashraf-web/Java_Project.git',
                            credentialsId: gitCredentialsId
                        ]]
                    ])
                }
            }
        }
        stage('Build and Unit Tests') {
            steps {
                script {
                    sh "chmod +x automations/bin/*.sh && automations/bin/compile.sh \"maven_extra_arguments=-s .m2/settings.xml\" \"version=$version\" \"sonar_url=$SONAR_URL\" \"sonar_project_key=$SONAR_PROJECT_KEY\" \"sonar_project_name=$SONAR_PROJECT_NAME\" && mkdir -p publish-artifacts && cp target/hello-world-web.war publish-artifacts/my-java-app-$version.war"
                }
            }
        }
    
    }
    post {
        success {
            archiveArtifacts 'target/hello-world-web.war'
        }
    }

}
