apiVersion: v1
kind: Service
metadata:
  name: jave-service
spec:
  ports:
    - port: 5060
      targetPort: 5060
      protocol: TCP
      nodePort: 30000
  selector:
    {{- include "mychart.selectorLabels" . | nindent 4 }}

  type: NodePort